package com.example.chen.translator.data.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.chen.translator.data.dao.Translation;

import com.example.chen.translator.data.dao.TranslationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig translationDaoConfig;

    private final TranslationDao translationDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        translationDaoConfig = daoConfigMap.get(TranslationDao.class).clone();
        translationDaoConfig.initIdentityScope(type);

        translationDao = new TranslationDao(translationDaoConfig, this);

        registerDao(Translation.class, translationDao);
    }
    
    public void clear() {
        translationDaoConfig.clearIdentityScope();
    }

    public TranslationDao getTranslationDao() {
        return translationDao;
    }

}
