package com.example.chen.translator.data.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TRANSLATION".
*/
public class TranslationDao extends AbstractDao<Translation, Long> {

    public static final String TABLENAME = "TRANSLATION";

    /**
     * Properties of entity Translation.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Input = new Property(1, String.class, "input", false, "INPUT");
        public final static Property Output = new Property(2, String.class, "output", false, "OUTPUT");
        public final static Property IsCollected = new Property(3, Boolean.class, "isCollected", false, "IS_COLLECTED");
    }


    public TranslationDao(DaoConfig config) {
        super(config);
    }
    
    public TranslationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TRANSLATION\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"INPUT\" TEXT," + // 1: input
                "\"OUTPUT\" TEXT," + // 2: output
                "\"IS_COLLECTED\" INTEGER);"); // 3: isCollected
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TRANSLATION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Translation entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String input = entity.getInput();
        if (input != null) {
            stmt.bindString(2, input);
        }
 
        String output = entity.getOutput();
        if (output != null) {
            stmt.bindString(3, output);
        }
 
        Boolean isCollected = entity.getIsCollected();
        if (isCollected != null) {
            stmt.bindLong(4, isCollected ? 1L: 0L);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Translation entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String input = entity.getInput();
        if (input != null) {
            stmt.bindString(2, input);
        }
 
        String output = entity.getOutput();
        if (output != null) {
            stmt.bindString(3, output);
        }
 
        Boolean isCollected = entity.getIsCollected();
        if (isCollected != null) {
            stmt.bindLong(4, isCollected ? 1L: 0L);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Translation readEntity(Cursor cursor, int offset) {
        Translation entity = new Translation( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // input
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // output
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0 // isCollected
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Translation entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setInput(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setOutput(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIsCollected(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Translation entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Translation entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Translation entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
